### PR TITLE
added ethbootnodes params to blockcreator, bridge and explorer

### PR DESCRIPTION
**Pull request by DylanVerstraete**

### CODE REVIEW

**Review by LeeSmet — CHANGES_REQUESTED** [review]
You made changes to capnp schemas, which requires a new id to be generated, see https://capnproto.org/language.html#unique-ids

**Comment by zaibon** [comment]
@LeeSmet actually that is not right:
>  In general, you would only specify an explicit ID for a declaration if that declaration has been renamed or moved and you want the ID to stay the same for backwards-compatibility.

So you don't have to change the ID for each modification.
Also since we only use capnp for the schema itself. We don't really care about it for our use case. So just making sure the ID is unique when creating the schema the first time is enough

**Comment by LeeSmet** [comment]
@zaibon I do recall having issues with templates because I forgot to update the schema ID. Furthermore, the text you links mentions unique ID's for declarations (i.e. schema fields, not the schema itself I guess).

While you are here, can you also take a look at the changes becasue part of me feels uneasy at how the self.data['ethbootnodes'] is there. Specifically, does this work if we don't specify this field in the data when creating the service? And also, it seems like now we will always pass the flag (`--ethbootnodes`), even when nothing is set here, which I don't want to do (the flag should only be set if there is a value there)

**Comment by DylanVerstraete** [comment]
New ID's are added.

**Review by LeeSmet — APPROVED** [review]

**Pull request merged**
